version: "3"
services:
  db:
    image: mysql:8.0.20
    container_name: mysql_container_twitch
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: "twitch"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/docker/volumes/dockerdb/_data
  front:
    build:
      context: ./front
    ports:
      - 3001:80
    volumes:
      - ./front/nginx/nginx.conf:/etc/nginx/nginx.conf
  server:
    build:
      context: ./server
    ports:
      - 3065:3065
    depends_on:
      - db
